### ISSUE TITLE
js/ts theme file with classes not obfuscating

### ISSUE THREAD

**Issue by jjjrmy** [jd1378/nuxt-obfuscator#1]
I am using FormKit on my Nuxt project, and they have [themes](https://themes.formkit.com/) that are within a `ts` file for each component. These values are not getting obfuscated.

**Comment by jd1378** [comment]
Well, I have no idea why it doesn't work
Maybe they have some kind of query on file path ?

**Comment by jd1378** [comment]
this is probably fixed in v2.0.1

**Comment by jjjrmy** [comment]
@jd1378 still not working. maybe there is additional config that needs to be done?
can we please re-open this issue?

**Comment by jd1378** [comment]
@jjjrmy can you setup a minimal reproduction repo with a simple setup with FormKit and obfuscator so I can investigate ?
